### ISSUE TITLE
Command failed with exit code 127

### ISSUE THREAD

**Issue by whalehub** [anshumanv/vueman.ga#9]
I cloned the repository with git today and installed vueman.ga by changing into the directory and running `yarn install`. That command worked fine, but all the other ones mentioned in the README.md file of this repository fail with exit code 127.

```
root@debian:/opt/vueman.ga# yarn run serve
yarn run v1.13.0
$ vue-cli-service serve
/bin/sh: 1: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@debian:/opt/vueman.ga# yarn run build
yarn run v1.13.0
$ vue-cli-service build
/bin/sh: 1: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@debian:/opt/vueman.ga# yarn run test
yarn run v1.13.0
error Command "test" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@debian:/opt/vueman.ga# yarn run lint
yarn run v1.13.0
$ vue-cli-service lint
/bin/sh: 1: vue-cli-service: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by whalehub** [comment]
The issue turns out to have been caused by some missing NPM packages. I was able to fix it with the following command:

```
npm install -g \
@vue/cli-plugin-babel \
@vue/cli-plugin-eslint \
@vue/cli-plugin-pwa \
@vue/cli-service \
@vue/cli-service-global \
vue-cli \
vue-cli-plugin-vuetify
```

However, now I get the following error:

```
root@debian:/opt/vueman.ga# yarn run build
yarn run v1.13.0
$ vue-cli-service build
 ERROR  Error: Cannot find module 'vuetify-loader/lib/plugin'
Error: Cannot find module 'vuetify-loader/lib/plugin'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:649:15)
    at Function.Module._load (internal/modules/cjs/loader.js:575:25)
    at Module.require (internal/modules/cjs/loader.js:705:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at module.exports (/usr/lib/node_modules/vue-cli-plugin-vuetify/index.js:8:33)
    at plugins.forEach (/usr/lib/node_modules/@vue/cli-service/lib/Service.js:80:7)
    at Array.forEach (<anonymous>)
    at Service.init (/usr/lib/node_modules/@vue/cli-service/lib/Service.js:79:18)
    at Service.run (/usr/lib/node_modules/@vue/cli-service/lib/Service.js:206:10)
    at Object.<anonymous> (/usr/lib/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by anshumanv** [comment]
Hi @whalehub, thanks for the report, this should not happen ideally, does it still occur?

**Comment by whalehub** [comment]
@anshumanv Yeah, it still occurs.

**Comment by whalehub** [comment]
@anshumanv Yeah, it still occurs. Any idea how to fix it?

**Comment by anshumanv** [comment]
Can you do - 
```sh
rm -r node_modules package-lock.json yarn.lock
yarn install
yarn start
```

And check once again?

Also, I've pushed a dockerfile which you can use to build it if the above fails, still unsure of the reason though, works well everywhere.

**Comment by whalehub** [comment]
@anshumanv Oh, I definitely prefer Docker. Could you push an official image to the Docker Hub so I can download it from there?
